### PR TITLE
[CORE-2068] update base app to v1.8.0 upstream

### PR DESCRIPTION
**Pull request by mwnnn**
changes differences with base v.1.8.0 (only contain our additional features)
(link version: https://github.com/scoutapp/scout-apm-laravel/compare/v1.8.0...mamitech:feature/CORE-2068-update-to-1-8?expand=1 )
image

### CODE REVIEW

**Comment by ahrezaldy** [comment]
I think all is good.. but some checks failed

**Comment by mwnnn** [comment]
image

result in scoutapm

**Comment by mwnnn** [comment]
this build run https://github.com/mamitech/scout-apm-laravel/pull/4/checks?check_run_id=2734560426 is also error on v1.8.0 upstream. Not sure why.
Tested on our server, it works

**Comment by vynhart** [comment]
looks good to me

**Pull request merged**
