### PR TITLE
KOS-15391 implemented sampling logic

### PR DESCRIPTION
**Pull request by gilbok**
- support SCOUT_SAMPLING_PER in .env, default value is 10
- renamed component name to mamitech/scout-apm-laravel.

https://mamikos.atlassian.net/browse/KOS-15391

### CODE REVIEW

**Comment by mwnnn** [comment]
`dev-master` is for `composer.json`, this means composer will fetch from branch `master`
as this target branch is `dev-master` , `composer.json` will need version `dev-dev-master`

what if we merge this into `master` then create new release? then we can use exact release version on `composer.json`

**Review by mwnnn — APPROVED** [review]

**Comment by gilbok** [comment]
I see. But I don't make any confuse with original's versioning 
and I also want to rebase ours against original `master` from time to time.
What branch name can be good choice?? @mwnnn 

Just using `master` and rebase it sometimes?

**Comment by mwnnn** [comment]
as the latest release version is `v1.5.0`, what if we 
- merge this into `master`
- create new release `v1.5.0.1`
- every time we rebase master / latest release, we create new release again, for example `v1.6.0.1`
- if we have additional feature, we increase the version we created, for example `v1.5.0.2`

**Comment by githubmamiteam** [comment]
@mwnnn So you can guarantee they will not use `v1.5.0.1`, right?

**Comment by gilbok** [comment]
@mwnnn OK, now I renamed component name.
So it's okay we use conflict version.

**Comment by gilbok** [comment]
I changed base to `master` and I will tag it `v1.5.0.1` after you merge this.
@mwnnn

**Pull request merged**
